FROM ubuntu:latest AS python
COPY ./Python/requirements.txt /requirements.txt
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y python3 python3-pip
RUN pip install --break-system-packages -r /requirements.txt

FROM python AS app
ENV FLASK_ENV=development
COPY ./Python /app
WORKDIR /app
ENTRYPOINT [ "python3", "/app/ApiCore.py" ]